#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: '{{ ansible_name }} | bundle | build' 
  hosts: containerone
  vars_files:
    - '../p1.yml'
    - 'vars/{{ target_environment }}.yml'
    - 'vars/global.yml'
  vars:
    module: "build"
    state_provider: "local"
    terraform_module_path: "{{ dir_git_tfcore }}"
    terraform_global_variables: "{{ dir_terraform }}/p1.tfvars"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
    name_bucket: '{{ target_environment }}-{{ name_cluster_vpc }}-openshift-artifacts'
    cloud_key_id_special: "{{ lookup('ini', 'aws_access_key_id section=default file={{ dir_artifacts }}/.aws/govcloud.credentials') }}"
    cloud_key_secret_special: "{{ lookup('ini', 'aws_secret_access_key section=default file={{ dir_artifacts }}/.aws/govcloud.credentials') }}"
  tasks:

    ####### Terraform Apply
    - name: '{{ ansible_name_module }} | terraform | Build VPC'
      terraform:
        state: absent
        project_path: "{{ terraform_module_path }}"
       #variables_file: "{{ terraform_global_variables }}"
      register: terraform_output

    ####### Destroy S3 Bucket
    - name: '{{ ansible_name_module }} | aws_s3 | Purge AWS S3 Artifact Bucket: {{ name_cluster_vpc }}-{{ cluster_domain }}'
      aws_s3:
        bucket: '{{ name_cluster_vpc }}-{{ cluster_domain }}'
        region: '{{ cloud_region }}'
        mode: delete
        aws_access_key: '{{ cloud_key_id_special }}'
        aws_secret_key: '{{ cloud_key_secret_special }}'
