#!/usr/local/bin/ansible-playbook --inventory=inventory.yaml
- name: '{{ name_vendor }} | Koffer | git.yml' 
  hosts: koffer
  vars_files:
    - 'vars/global.yml'
    - 'vars/git.yml'
  vars:
    module: "git"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
  tasks:

    - name: '{{ ansible_name_module }} | git:clone | Clone Git Dependencies' 
      git:
        clone: yes
        version: "{{ item.branch }}"
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
        update: true
        force: yes
      with_items:
        - "{{ ansiblerepos }}"
        - "{{ terraformrepos }}"
    
    - name: '{{ ansible_name_module }} | shell:terraform.init | Initilize terraform modules'
      shell: 
        cmd: terraform init
        chdir: "{{ item.dest }}"
      with_items:
        - "{{ terraformrepos }}"
