#!/usr/local/bin/ansible-playbook
- hosts: koffer
  environment:
    PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  tasks:
    # download collector dependencies
    - import_role:
        name: sparta.collector.dependencies
    # run operators artifact collector
    - import_role:
        name: sparta.collector.operators
    # run sparta iac artifact collector
    - import_role:
        name: sparta.collector.iac
    # run openshift artifact collector
    - import_role:
        name: sparta.collector.openshift
    # run cloudctl artifact collector
    - import_role:
        name: sparta.collector.cloudctl
    # run openshift artifact collector
    - import_role:
        name: sparta.collector.bundle
