#!/usr/local/bin/ansible-playbook --inventory=inventory.yaml
- name: '{{ name_vendor }} | Koffer | images.yml' 
  hosts: koffer
  vars_files:
    - 'vars/global.yml'

  vars:
    module: "images"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"

  tasks:

    - name: '{{ ansible_name_module }} | file:directory | Create binary path(s)' 
      file:
        path: '{{ item }}'
        state: directory
        mode: '0744'
        recurse: yes
      with_items:
        - '{{ tpdk_bin }}'

    - name: '{{ ansible_name_module }} | get_url:url | Download openshift-install binary | {{ version_openshift }}'
      unarchive:
        src: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ version_openshift }}/openshift-install-linux.tar.gz"
        dest: '{{ tpdk_bin }}'
        remote_src: yes
        mode: 0775
    
    - name: '{{ ansible_name_module }} | get_url:url | Download oc binary | {{ version_openshift }}'
      unarchive:
        src: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ version_openshift }}/openshift-client-linux.tar.gz"
        dest: '{{ tpdk_bin }}'
        remote_src: yes
        mode: 0775
