#!/usr/local/bin/ansible-playbook --inventory=inventory.yaml
- name: '{{ name_vendor }} | Koffer | tree.yml' 
  hosts: koffer
  vars_files:
    - 'vars/global.yml'
    - 'vars/git.yml'
  vars:
    module: "tree"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
  tasks:

    - name: '{{ ansible_name_module }} | file | Create Directory Structure' 
      file:
        path: '{{ item }}'
        state: directory
        mode: '0775'
        recurse: yes
      with_items:
        - '{{ local_home }}/bundle'
        - '{{ dir_platform }}/terraform'
        - '{{ dir_platform }}/ansible'
        - '{{ dir_platform }}/mirror'
        - '{{ dir_platform }}/images'
        - '{{ dir_platform }}/nginx'
        - '{{ dir_platform }}/secrets'
        - '{{ dir_platform }}/secrets/ssh'
        - '{{ dir_platform }}/secrets/registry'
        - '{{ dir_platform }}/secrets/registry/ssl'
        - '{{ dir_platform }}/secrets/registry/auth'
    
    - name: '{{ ansible_name_module }} | template | Stage CloudCtl Startup Assets' 
      template:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
        mode: '{{ item.mode }}'
      with_items:
        - { mode: '0775', src: '{{ dir_koffer }}/collector/templates/registry/etc-docker-registry-config.yml.j2', dest: '{{ dir_platform }}/mirror/config.yml' }
        - { mode: '0775', src: '{{ dir_koffer }}/collector/templates/bin/konductor.sh.j2', dest: '/tmp/konductor.sh' }
        - { mode: '0775', src: '{{ dir_koffer }}/collector/templates/pod/cloudctl.yml.j2', dest: '/tmp/cloudctl.yml' }
        - { mode: '0775', src: '{{ dir_koffer }}/collector/templates/bin/answer.sh.j2', dest: '/tmp/answer.sh' }
