#!/usr/local/bin/ansible-playbook --inventory=inventory.yaml
- name: '{{ name_vendor }} | Koffer | tree.yml' 
  hosts: koffer
  vars_files:
    - 'vars/global.yml'
  vars:
    module: "tree"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
  tasks:

    - name: '{{ ansible_name_module }} | file | Purge pre-existing artifacts'
      file:
        path: '{{ item }}'
        state: absent
      loop:
        - '{{ dir_platform }}'
    
    - name: '{{ ansible_name_module }} | file | Create Directory Structure' 
      file:
        path: '{{ item }}'
        state: directory
        mode: '0775'
        recurse: yes
      with_items:
        - '{{ local_home }}/bundle'
        - '{{ dir_platform }}/iac'
